services:
  - type: web
    name: serveease
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      flask db upgrade && gunicorn app:app
    envVars:
      - key: FLASK_APP
        value: app
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: your-database-name
          property: connectionString
