"""Add tracking_number fields with proper constraint names

Revision ID: 3f8832827274
Revises: 5107b7d3f00c
Create Date: 2025-06-25 07:50:04.178211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f8832827274'
down_revision = '5107b7d3f00c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_tracking', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint('uq_tracking_number_appointment', ['appointment_tracking'])


    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback_tracking', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint('uq_tracking_number_feedback', ['feedback_tracking'])

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_tracking', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint('uq_tracking_number_payment', ['payment_tracking'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('payment_tracking')

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('feedback_tracking')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('appointment_tracking')

    # ### end Alembic commands ###
