"""Enhance Payment with method, tracking number

Revision ID: 40208d315309
Revises: 42d8a9cbfb48
Create Date: 2025-06-26 16:50:47.106421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40208d315309'
down_revision = '42d8a9cbfb48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('method', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('tracking_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('purpose')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('purpose', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('transaction_id', sa.VARCHAR(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.alter_column('tracking_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('date')
        batch_op.drop_column('method')

    # ### end Alembic commands ###
