"""Added date created on Feedback

Revision ID: 42d8a9cbfb48
Revises: a5524e522313
Create Date: 2025-06-26 16:40:40.174944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42d8a9cbfb48'
down_revision = 'a5524e522313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
