"""Updates

Revision ID: 5107b7d3f00c
Revises: 51ddff5a3178
Create Date: 2025-06-25 07:12:38.780903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5107b7d3f00c'
down_revision = '51ddff5a3178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('document_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_request', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
